// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJSx6lg67oMl928lyiLgfqdjU4J2yQkQ',
    appId: '1:124410905468:android:fa8c3518c73d541b',
    messagingSenderId: '124410905468',
    projectId: 'smart-lib',
    databaseURL: 'https://smart-lib.firebaseio.com',
    storageBucket: 'smart-lib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7e3byAHep0S0YMhtfNJLkw5ruvfj7EUs',
    appId: '1:124410905468:ios:0b593ed469b5c5fc',
    messagingSenderId: '124410905468',
    projectId: 'smart-lib',
    databaseURL: 'https://smart-lib.firebaseio.com',
    storageBucket: 'smart-lib.appspot.com',
    androidClientId: '124410905468-dm9ef3miqd16gu0bqp5e1lqo6mempvsc.apps.googleusercontent.com',
    iosClientId: '124410905468-4l6gi7n1vt3cskk1rj57cgsrt7as2lsg.apps.googleusercontent.com',
    iosBundleId: 'com.apps-foundry.eperpuswl.id.smartlibrary',
  );
}
